description: ""
author: "TecOrb-Developers"

runs:
  using: "composite"
  steps: 
    - name: Echo
      shell: bash
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash

inputs:
  github_user_name:
    description: "TecOrb-Developers"
    required: true
  outputs:
    required: false
    default: null
    description: |
      list of files to generate.
      one file per line. Each output can be customized with options as query string.

       supported query string options:

      - palette:      A preset of color, one of [github, github-dark, github-light]
      - color_snake:  Color of the snake
      - color_dots:   Coma separated list of dots color. 
                      The first one is 0 contribution, then it goes from the low contribution to the highest.
                      Exactly 5 colors are expected.
      example:
        outputs: |
          dark.svg?TecOrb-Developers=github-dark&color_snake=blue
          light.svg?color_snake=#7845ab
          ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
