## GitHub Action for generating a contribution graph with a snake eating your contributions.
## GitHub Action для создания графика вкладов со змеей, пожирающей ваши взносы.

name: snake animation

on:
  # run automatically every 12 hours
  schedule:
    - cron: "0 */12 * * *"

  # allows to manually run the job at any time
  workflow_dispatch:

  # run on every push on the master branch
  push:
    branches:
    - main



jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      # - name: Generate github-contribution-snake.svg
        # uses: Platane/snk/svg-only@v3
        # uses: actions/checkout@v3
        # uses: Platane/snk@aebc3a92857730857d5a96010a3538f16bbec662  # v3.0.0
      - uses: Platane/snk@aebc3a92857730857d5a96010a3538f16bbec662
        id: snake-gif
        with:
          
          github_user_name: TecOrb-Developers
          outputs: |
            gif_out_path: dist/github-contribution-snake.gif
            svg_out_path: dist/github-contribution-snake.svg
           # these next 2 lines generate the files on a branch called "output". This keeps the main branch from cluttering up.
         
          # outputs: |
          #   dist/github-contribution-snake.svg
          #   dist/github-contribution-snake-dark.svg?palette=github-dark

      # show the status of the build. Makes it easier for debugging (if there's any issues).
      - run: git status

      # push the content of <build_dir> to a branch


      - name: Push changes
        uses: actions/checkout@v3  # v3.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          
      # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as github page
      - name: Push github-contribution-snake.svg to the output branch
        # uses: crazy-max/ghaction-github-pages@v2.6.0
        uses: actions/checkout@v3  # v3.0.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
